defaults: &defaults
  working_directory: ~/app
  docker:
    - image: cypress/browsers:chrome67

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
        keys:
          - cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
        name: Install Dependencies
        command: npm ci
      - run: npm run cy:verify
      - save_cache:
        key: cache-{{ .Branch }}-{{ checksum "package.json" }}
        paths:
          - ~/.npm
          - ~/.cache
      - persist_to_workspace:
        root: ~/
        paths:
          - app
          - .cache/Cypress
  test_chorme:
    <<: *defaults
    environment:
      CYPRESS_RECORD_KEY: 'a356e439-1fac-4f7d-9dad-97fc9c827a57'
    steps:
      - attach_workspace:
        at: ~/
      - run: npm run e2e:record -- --group $CIRCLE_JOB --browser chorme

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test_chorme:
        requires:
          - build
